<theme extends="bootstrap" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="platform:/plugin/com.ibm.designer.domino.stylekits/schema/stylekit.xsd">
	<resources>
		<styleSheet type="text/css" href="/style.css"/>
	</resources>

	<control>
		<name>ViewRoot</name>
		<property>
			<name>pageIcon</name>
			<value>/$Icon</value>
		</property>
		<property>
			<name>pageTitle</name>
			<value>Portfolio</value>
		</property>
	</control>
</theme>
